version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: 'neo4j/secret'
    ports:
      - "7687:7687"
      - "7474:7474"
    restart: always
