version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: 'neo4j/secret'
      NEO4J_dbms_connector_bolt_advertised__address: 'localhost:7687'
      NEO4J_dbms_connector_http_advertised__address=: 'localhost:7474'
    ports:
      - "7687:7687"
      - "7474:7474"
    restart: always
